version: 2
jobs: 
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t cmmattd/testapp:$CIRCLE_BUILD_NUM .
      - run: docker push cmmattd/testapp:$CIRCLE_BUILD_NUM
      - run: docker build -t cmmattd/testapp .
      - run: docker push cmmattd/testapp
