version: 2
jobs: 
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t cmmattd/testapp:$CIRCLE_BUILD_NUM .
      - run: docker push cmmattd/testapp:$CIRCLE_BUILD_NUM
      - run: docker build -t cmmattd/testapp .
      - run: docker push cmmattd/testapp
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - run: chmod +x kubectl
      - run: sudo apt-get -y install gnupg
      - run: echo $GPG_PASS | gpg -d --passphrase-fd 0  --batch --yes kube.gpg > kubeconfig
      - run: env KUBECONFIG=kubeconfig PATH=$PATH:. kubectl replace -f kubernetes/deployment.yml 
