apiVersion: v1
kind: Service
metadata: 
  name: test-application
  labels:
    run: test-application
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    run: test-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application
  labels:
    app: nodetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodetest
  template:
    metadata:
      labels:
        app: nodetest
    spec:
      containers:
      - name: nodetest
        image: cmmattd/testapp
        ports:
        - containerPort: 3000
        
